# Generated by Django 5.2.9 on 2025-12-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('resim', models.ImageField(upload_to='fotograflar/')),
                ('aciklama', models.TextField(blank=True)),
                ('tarih', models.DateField()),
            ],
        ),
    ]
